add_irust_cmd_to_history = true
add_shell_cmd_to_history = false
ok_color = "blue"
eval_color = "white"
irust_color = "dark_blue"
irust_warn_color = "cyan"
out_color = "red"
shell_color = "dark_yellow"
err_color = "dark_red"
input_color = "yellow"
insert_color = "white"
welcome_msg = ""
welcome_color = "dark_blue"
ra_inline_suggestion_color = "cyan"
ra_suggestions_table_color = "green"
ra_selected_suggestion_color = "dark_red"
ra_max_suggestions = 5
first_irust_run = false
enable_rust_analyzer = false
toolchain = "Default"
check_statements = true
auto_insert_semicolon = true
replace_marker = "$out"
replace_output_with_marker = false
input_prompt = "In: "
output_prompt = "Out: "
activate_scripting = false
executor = "Sync"
evaluator = ["""
println!(\"{:?}\", {
""", """

});"""]
compile_time = false
main_result = "Unit"
show_warnings = false
edition = "E2021"
debugger = "LLDB"
shell_interpolate = true
local_server = false
local_server_adress = "127.0.0.1:9000"
theme = "default"
compile_mode = "Debug"
new_lines_after_output = 1
