echo '__      __  __    __  __    __'
echo '/  \    /  |/  \  /  |/  |  /  | @name:    ynx.aron'
echo '$$  \  /$$/ $$  \ $$ |$$ |  $$ | @email:   ynx.aron@outlook.com'
echo ' $$  \/$$/  $$$  \$$ |$$  \/$$/  @desktop: CachyOS'
echo '  $$  $$/   $$$$  $$ | $$  $$<   @kernal:  cachyos-6.13.1-2'
echo '   $$$$/    $$ $$ $$ |  $$$$  \  @uptime: $(uptime --pretty)'
echo '    $$ |    $$ |$$$$ | $$ /$$  |'
echo '    $$ |    $$ | $$$ |$$ |  $$ |'
echo '    $$/     $$/   $$/ $$/   $$/ '
